apiVersion: v1
kind: Pod
metadata:
  name: n-audit-sentinel
  labels:
    app: n-audit-sentinel
spec:
  serviceAccountName: n-audit-sentinel
  securityContext:
    runAsUser: 0
  initContainers:
  - name: init-ssh-key
    image: n-audit-sentinel:beta-v1.0.0-beta
    command:
    - /bin/bash
    - -c
    - |
      mkdir -p /var/lib/n-audit/signing
      chmod 700 /var/lib/n-audit/signing
      if [ ! -f /var/lib/n-audit/signing/id_ed25519 ]; then
        ssh-keygen -t ed25519 -N "" -f /var/lib/n-audit/signing/id_ed25519 -C "n-audit-sentinel@k8s"
        chmod 600 /var/lib/n-audit/signing/id_ed25519
        chmod 644 /var/lib/n-audit/signing/id_ed25519.pub
        echo "[Init] SSH signing key generated at /var/lib/n-audit/signing/id_ed25519"
      else
        echo "[Init] SSH signing key already exists"
      fi
    volumeMounts:
    - name: data
      mountPath: /var/lib/n-audit
  containers:
  - name: sentinel
    image: n-audit-sentinel:beta-v1.0.0-beta
    stdin: true
    tty: true
    env:
    - name: SSH_SIGN_KEY_PATH
      value: "/var/lib/n-audit/signing/id_ed25519"
    volumeMounts:
    - name: data
      mountPath: /var/lib/n-audit
  volumes:
  - name: data
    hostPath:
      path: /mnt/n-audit-data
      type: DirectoryOrCreate
  restartPolicy: Always
